# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "false"
image:
  pullPolicy: IfNotPresent
pv:
  region: eu-west-1
  zone: eu-west-1a
  fsType: ext4
  volumeID: ""
  storage: 50Gi
images:
  kafka: wurstmeister/kafka:0.8.2.0
  zookeeper: wurstmeister/zookeeper
  kafkaProxy: coco/kafka-proxy:v1.0.0
ports:
  kafka: 9092
  zookeeper: 2181
  kafkaProxy: 8082
ephemeral_storage: false
resources:
  requests:
    memory: 256Mi
  limits:
    memory: 2Gi
