apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.service.name }} 
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}" 
    visualize: "true" 
    app: {{ .Values.service.name }} 
spec:
  replicas: 1 # keeping a single replica in the stateful set
  serviceName: {{.Values.service.name}}
  selector: 
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true" 
    spec:
{{- if .Values.eksCluster }}
      tolerations:
      - key: ng-kafka
        operator: Equal
        value: "false"
        effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/ng-kafka
                  operator: In
                  values:
                  - "true"
{{- else }}
      tolerations:
      # Making sure that Kafka will be scheduled on dedicated nodes. These nodes are tainted by the provisioner.
      - key: "dedicated"
        operator: "Equal"
        value: "kafka"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kube-aws.coreos.com/role
                operator: In
                values:
                - kafka-worker
{{- end }}
      containers:
      - name: kafka
        image: {{ .Values.images.kafka }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "16777216"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "16777216"
        - name: DOCKER_HOST
          value: "localhost:2375"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "{{.Values.service.name}}-0.kafka.default.svc.cluster.local"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{.Values.service.name}}-zookeeper:{{ .Values.ports.zookeeper }}"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_PORT
          value: "{{ .Values.ports.kafka }}"
        - name: KAFKA_ADVERTISED_PORT
          value: "{{ .Values.ports.kafka }}"
        {{- if eq .Values.ephemeral_storage true }}
        - name: KAFKA_LOG_RETENTION_BYTES
          value: "134217728"
        {{- end }}
        ports:
        - containerPort: {{ .Values.ports.kafka }}
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: {{ .Values.ports.kafka }}
        volumeMounts:
         - name: kafka-persistent-storage
           mountPath: /kafka
           subPath: kafka-data
        resources: 
{{ toYaml .Values.kafkaResources | indent 12 }}
      volumes:
        - name: kafka-persistent-storage
        {{- if eq .Values.ephemeral_storage true }}
          emptyDir: {}
        {{- else }}
          persistentVolumeClaim:
            claimName: "{{ .Values.service.name }}-pvc"
        {{- end }}
