# Headless service for kafka driving the stateful set DNS
kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    app: {{.Values.service.name}}
    visualize: "true"
    hasHealthcheck: "false"
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.ports.kafka }}
      name: "kafka"
      targetPort: {{ .Values.ports.kafka }}
  selector:
    app: {{ .Values.service.name }}
