---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-rest-proxy-msk
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}-rest-proxy-msk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}-rest-proxy-msk
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}-rest-proxy-msk
        visualize: "true"
    spec:
      containers:
      - name: kafka-proxy-msk
        image: confluentinc/cp-kafka-rest:5.2.3
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: "z-2.upp-k8s-kafka.729803.c2.kafka.eu-west-1.amazonaws.com:2181,z-1.upp-k8s-kafka.729803.c2.kafka.eu-west-1.amazonaws.com:2181,z-3.upp-k8s-kafka.729803.c2.kafka.eu-west-1.amazonaws.com:2181"
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "b-2.upp-k8s-kafka.729803.c2.kafka.eu-west-1.amazonaws.com:9094,b-3.upp-k8s-kafka.729803.c2.kafka.eu-west-1.amazonaws.com:9094,b-1.upp-k8s-kafka.729803.c2.kafka.eu-west-1.amazonaws.com:9094"
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082
        - name: KAFKA_REST_HOST_NAME
          value: localhost
        - name: KAFKA_REST_CLIENT_SECURITY_PROTOCOL
          value: SSL
        - name: KAFKA_REST_FETCH_MESSAGE_MAX_BYTES
          value: "16777216"
        - name: KAFKA_REST_CONSUMER_REQUEST_MAX_BYTES
          value: "17825792"
        - name: KAFKA_REST_MAX_REQUEST_SIZE
          value: "17825792"
        ports:
        - containerPort: {{ .Values.ports.kafkaProxy }}
        livenessProbe:
          initialDelaySeconds: 90
          tcpSocket:
            port: {{ .Values.ports.kafkaProxy }}
        resources:
{{ toYaml .Values.kafkaProxyResources | indent 12 }}
