# Headless service for kafka driving the stateful set DNS
kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}} 
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    app: {{.Values.service.name}}
    visualize: "true" 
    hasHealthcheck: "false"
  annotations:
    # https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L56
    # create endpoints for unready pods - mongo needs to resolve the cluster member addresses on startup
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports: 
    - port: {{ .Values.ports.kafka }}
      name: "kafka"
      targetPort: {{ .Values.ports.kafka }}
  selector:
    app: {{ .Values.service.name }} 
