kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}} 
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{.Values.service.name}}
    visualize: "true" 
    hasHealthcheck: "{{ .Values.service.hasHealthcheck }}" 
spec:
  ports: 
    - port: {{ .Values.ports.kafkaProxy }}
      name: "kafka-proxy"
      targetPort: {{ .Values.ports.kafkaProxy }}
    - port: {{ .Values.ports.kafka }}
      name: "kafka"
      targetPort: {{ .Values.ports.kafka }}
    - port: {{ .Values.ports.zookeeper }}
      name: "zookeeper"
      targetPort: {{ .Values.ports.zookeeer }}
  selector: 
    app: {{ .Values.service.name }} 
