apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    failure-domain.beta.kubernetes.io/region: {{ .Values.pv.region }}
    failure-domain.beta.kubernetes.io/zone: {{ .Values.pv.zone }}
  name: "{{ .Values.service.name }}-pv"
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: {{ .Values.pv.fsType }}
    volumeID: {{ .Values.pv.volumeID }}
  capacity:
    storage: {{ .Values.pv.storage }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: "{{ .Values.service.name }}-pvc"
    namespace: default
  persistentVolumeReclaimPolicy: Retain
