{{- if not .Values.ephemeral_storage }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.service.name }}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: {{ .Values.pv.storage }}
  selector:
    matchLabels:
      provisioned-for: "kafka"
{{- end }}
